import type { MetadataRoute } from "next";

/**
 * Installable PWA. Farmers add it to the home screen — no Play Store, no APK
 * to sideload, and updates land without anyone reinstalling anything.
 *
 * Every file named here is generated by `src/lib/icon-png.ts` and lives in
 * `public/`. They used to be named here and not exist, which 404'd both icons
 * and suppresses the install prompt on some Androids.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Dairy Manager",
    short_name: "Dairy",
    description: "Milk, herd, feed, health and money for a working dairy farm.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#eef1ec",
    theme_color: "#0e5a47",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Drawn smaller inside the same square, because a launcher crops a
      // maskable icon to its own shape and only the middle 80% is safe.
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    // One tap from the home screen to the screen that runs twice a day.
    shortcuts: [
      { name: "Record a milking", short_name: "Milking", url: "/milk" },
      { name: "Today's jobs", short_name: "Jobs", url: "/alerts" },
    ],
  };
}
