/**
 * M1 — Herd & Animals.
 *
 * The register, and the derived lifecycle on top of it. Class is never a
 * column: every read assembles `AnimalFacts` from the events (calvings,
 * services, pregnancy checks, dry-offs, weights) and asks
 * `domain/animal.ts` what that animal *is* today.
 *
 * NOTE ON THE `"use server"` PLACEMENT. The directive is on each mutating
 * function, not at the top of the file. A file-level directive would publish
 * `listHerd(session, …)` as a POST endpoint, and a caller who hands us a
 * session object is a caller who can forge one. Queries here take the session
 * the *caller* already verified; only the FormData actions are endpoints, and
 * each of those re-derives the session itself.
 */
import { db } from "@/db";
import * as s from "@/db/schema";
import { and, eq, inArray, isNull } from "drizzle-orm";
import { updateTag } from "next/cache";
import { z } from "zod";

import {
  requireCapability,
  assertOwned,
  guard,
  actionOk,
  actionError,
  type ActionResult,
  type Session,
} from "@/lib/dal";
import { newId, refCode, REF_PREFIX } from "@/lib/ids";
import { dec, num } from "@/lib/money";
import {
  addDays,
  ageDays,
  ageMonths,
  daysBetween,
  today,
  type ISODate,
} from "@/lib/domain/dates";
import {
  deriveClass,
  deriveReproStatus,
  daysInMilk as dimOf,
  isMilking,
  CLASS_LABEL,
  WEANING_AGE_MONTHS,
  type AnimalFacts,
} from "@/lib/domain/animal";
import { breedingCalendar, calvingInterval, servicesPerConception } from "@/lib/domain/breeding";
import {
  KENYA_ROUTINES,
  checkRoutineEligibility,
  COLOSTRUM_DAYS,
  type RoutineRule,
} from "@/lib/domain/health";
import type { AnimalClass, ReproStatus } from "@/db/schema";

/* ================================================================== */
/* Reference codes                                                     */
/* ================================================================== */

/**
 * `REF_PREFIX` has no herd entries (see the report) — these are local so the
 * shared file stays untouched while four agents are building.
 */
const HERD_REF = { ANIMAL: "AN", WEIGHT: "WT" } as const;

/** Alerts generated by the first-year schedule all carry this prefix. */
export const ROUTINE_ALERT_PREFIX = "ROUTINE_";

/* ================================================================== */
/* Small form helpers                                                  */
/* ================================================================== */

/** FormData → object, dropping blanks so `.optional()` behaves as expected. */
export function formObject(formData: FormData): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of formData.entries()) {
    if (typeof v !== "string") continue;
    const t = v.trim();
    if (t !== "") out[k] = t;
  }
  return out;
}

const isoDate = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "Use a date like 2026-08-03.");

const checkbox = z
  .string()
  .optional()
  .transform((v) => v === "on" || v === "true" || v === "1" || v === "yes");

/* ================================================================== */
/* Receipts (R6)                                                       */
/* ================================================================== */

/**
 * Write the receipt for a saved record, once.
 *
 * The receipt row reuses the record's own id, so a double-flush from the
 * offline outbox lands on the same primary key and the ORIGINAL reference code
 * is handed back. A receipt whose code changed on a retry would be worse than
 * no receipt at all — it is the thing the farmer writes in the notebook.
 */
export async function writeReceipt(
  session: Session,
  opts: { id: string; prefix: string; kind: string; summary: string; payload?: unknown },
): Promise<string> {
  const existing = await db.query.receipt.findFirst({
    where: and(eq(s.receipt.id, opts.id), eq(s.receipt.farmId, session.farmId)),
  });
  if (existing) return existing.refCode;

  const ref = refCode(opts.prefix);
  await db
    .insert(s.receipt)
    .values({
      id: opts.id,
      farmId: session.farmId,
      refCode: ref,
      kind: opts.kind,
      summary: opts.summary,
      actorId: session.userId,
      at: new Date(),
      payload: (opts.payload ?? null) as never,
    })
    .onConflictDoNothing();
  return ref;
}

/* ================================================================== */
/* Event sources — everything class derivation is built from           */
/* ================================================================== */

export type AnimalRow = typeof s.animal.$inferSelect;
type CalvingRow = typeof s.calving.$inferSelect & {
  outcomes: (typeof s.calvingOutcome.$inferSelect)[];
};
type ServiceRow = typeof s.service.$inferSelect;
type PdRow = typeof s.pregnancyCheck.$inferSelect;
type DryOffRow = typeof s.dryOff.$inferSelect;
type WeightRow = typeof s.weightObservation.$inferSelect;
type ExitRow = typeof s.animalExit.$inferSelect;
type HeatRow = typeof s.heatObservation.$inferSelect;

export interface AnimalEvents {
  /** Ascending by date throughout — callers rely on it. */
  calvings: CalvingRow[];
  services: ServiceRow[];
  pds: PdRow[];
  dryOffs: DryOffRow[];
  weights: WeightRow[];
  heats: HeatRow[];
  exits: ExitRow[];
}

function emptyEvents(): AnimalEvents {
  return { calvings: [], services: [], pds: [], dryOffs: [], weights: [], heats: [], exits: [] };
}

export interface HerdSources {
  animals: AnimalRow[];
  events: Map<string, AnimalEvents>;
}

function bucket(map: Map<string, AnimalEvents>, animalId: string): AnimalEvents {
  let e = map.get(animalId);
  if (!e) {
    e = emptyEvents();
    map.set(animalId, e);
  }
  return e;
}

/**
 * Load the whole farm's animals and their events in a fixed number of queries.
 *
 * A Kenyan smallholder-commercial herd is tens of animals, low hundreds at the
 * top end, so seven scans and an in-memory group-by is both faster and far
 * easier to reason about than seven correlated sub-selects. `farmId` is in
 * every single `where` — that is the tenancy boundary, not a nicety.
 */
export async function loadHerdSources(
  session: Session,
  opts: { animalIds?: string[] } = {},
): Promise<HerdSources> {
  const farmId = session.farmId;
  const ids = opts.animalIds;
  if (ids && ids.length === 0) return { animals: [], events: new Map() };

  const animals = await db
    .select()
    .from(s.animal)
    .where(ids ? and(eq(s.animal.farmId, farmId), inArray(s.animal.id, ids)) : eq(s.animal.farmId, farmId));

  const known = new Set(animals.map((a) => a.id));
  const events = new Map<string, AnimalEvents>();
  for (const a of animals) events.set(a.id, emptyEvents());

  const [calvings, outcomes, services, pds, dryOffs, weights, heats, exits] = await Promise.all([
    db.select().from(s.calving).where(eq(s.calving.farmId, farmId)),
    db.select().from(s.calvingOutcome).where(eq(s.calvingOutcome.farmId, farmId)),
    db.select().from(s.service).where(eq(s.service.farmId, farmId)),
    db.select().from(s.pregnancyCheck).where(eq(s.pregnancyCheck.farmId, farmId)),
    db.select().from(s.dryOff).where(eq(s.dryOff.farmId, farmId)),
    db.select().from(s.weightObservation).where(eq(s.weightObservation.farmId, farmId)),
    db.select().from(s.heatObservation).where(eq(s.heatObservation.farmId, farmId)),
    db.select().from(s.animalExit).where(eq(s.animalExit.farmId, farmId)),
  ]);

  const outcomesByCalving = new Map<string, (typeof s.calvingOutcome.$inferSelect)[]>();
  for (const o of outcomes) {
    const list = outcomesByCalving.get(o.calvingId) ?? [];
    list.push(o);
    outcomesByCalving.set(o.calvingId, list);
  }

  for (const c of calvings) {
    if (!known.has(c.damId)) continue;
    bucket(events, c.damId).calvings.push({ ...c, outcomes: outcomesByCalving.get(c.id) ?? [] });
  }
  for (const r of services) if (known.has(r.animalId)) bucket(events, r.animalId).services.push(r);
  for (const r of pds) if (known.has(r.animalId)) bucket(events, r.animalId).pds.push(r);
  for (const r of dryOffs) if (known.has(r.animalId)) bucket(events, r.animalId).dryOffs.push(r);
  for (const r of weights) if (known.has(r.animalId)) bucket(events, r.animalId).weights.push(r);
  for (const r of heats) if (known.has(r.animalId)) bucket(events, r.animalId).heats.push(r);
  for (const r of exits) if (known.has(r.animalId)) bucket(events, r.animalId).exits.push(r);

  for (const e of events.values()) {
    e.calvings.sort((a, b) => a.calvedOn.localeCompare(b.calvedOn));
    e.services.sort((a, b) => a.servedOn.localeCompare(b.servedOn));
    e.pds.sort((a, b) => a.checkedOn.localeCompare(b.checkedOn));
    e.dryOffs.sort((a, b) => a.driedOn.localeCompare(b.driedOn));
    e.weights.sort((a, b) => a.observedOn.localeCompare(b.observedOn));
    e.heats.sort((a, b) => a.observedAt.getTime() - b.observedAt.getTime());
    e.exits.sort((a, b) => a.exitDate.localeCompare(b.exitDate));
  }

  return { animals, events };
}

/** A calving with every outcome an abortion is a pregnancy loss, not a parity. */
export function isAbortionCalving(c: CalvingRow): boolean {
  return c.outcomes.length > 0 && c.outcomes.every((o) => o.outcome === "ABORTION");
}

/**
 * Assemble the facts `deriveClass` / `deriveReproStatus` need, **as of a date**.
 *
 * Everything after `asOf` is invisible, which is what makes
 * `herdInventoryReconciliation` and `classAtExit` honest rather than
 * retrospectively rewritten by later events.
 */
export function factsFor(animal: AnimalRow, ev: AnimalEvents, asOf: ISODate): AnimalFacts {
  const calvings = ev.calvings.filter((c) => c.calvedOn <= asOf && !isAbortionCalving(c));
  const services = ev.services.filter((r) => r.servedOn <= asOf);
  const pds = ev.pds.filter((r) => r.checkedOn <= asOf);
  const dryOffs = ev.dryOffs.filter((r) => r.driedOn <= asOf);
  const weights = ev.weights.filter((r) => r.observedOn <= asOf && r.weightKg != null);
  const exit = ev.exits.find((r) => r.exitDate <= asOf) ?? null;

  const lastCalvingOn = calvings.length ? calvings[calvings.length - 1].calvedOn : null;
  const lastService = services.length ? services[services.length - 1] : null;
  const positives = pds.filter((p) => p.result === "POSITIVE");
  const negatives = pds.filter((p) => p.result === "NEGATIVE");

  // The expected calving date belongs to the service she is currently carrying.
  // Prefer the service a positive diagnosis actually pointed at.
  let edd: ISODate | null = lastService?.expectedCalvingOn ?? null;
  const lastPositive = positives.length ? positives[positives.length - 1] : null;
  if (lastPositive?.serviceId) {
    const tied = services.find((r) => r.id === lastPositive.serviceId);
    if (tied?.expectedCalvingOn) edd = tied.expectedCalvingOn;
  }
  if (!edd && lastService) {
    edd = breedingCalendar(lastService.servedOn, animal.primaryBreed).expectedCalvingOn;
  }

  return {
    sex: animal.sex,
    dateOfBirth: animal.dateOfBirth,
    castrated: animal.castrated,
    classOverride: animal.classOverride,
    parity: calvings.length,
    lastCalvingOn,
    lastServiceOn: lastService?.servedOn ?? null,
    pdPositiveOn: lastPositive?.checkedOn ?? null,
    pdNegativeOn: negatives.length ? negatives[negatives.length - 1].checkedOn : null,
    driedOffOn: dryOffs.length ? dryOffs[dryOffs.length - 1].driedOn : null,
    expectedCalvingOn: edd,
    latestWeightKg: weights.length ? num(weights[weights.length - 1].weightKg) : null,
    culled: exit?.reason === "CULLED",
  };
}

/* ================================================================== */
/* The first-year schedule (R7)                                        */
/* ================================================================== */

export interface ScheduleItem {
  routine: string;
  label: string;
  dueOn: ISODate;
  /** After this date the window has closed — S19 and disbudding both have one. */
  windowClosesOn: ISODate | null;
  onceInLifetime: boolean;
  /** One person, one animal, one action, one deadline. */
  action: string;
  note?: string;
  severity: "INFO" | "WARN" | "CRITICAL";
  assignedRole: "HERDSMAN" | "MANAGER";
}

const VACCINE_ROUTINES = new Set(["S19", "ECF_ITM", "FMD", "LSD", "ANTHRAX_BQ"]);

function routineAction(rule: RoutineRule, dueOn: ISODate, closesOn: ISODate | null): string {
  const window = closesOn ? ` Do it before ${closesOn}.` : "";
  return `${rule.label} — due ${dueOn}.${window}`;
}

/**
 * One registration in, a year of reminders out.
 *
 * Eligibility is checked *at the date the dose would fall*, which is what keeps
 * S19 off a bull calf's list rather than putting it there and refusing it four
 * months later.
 */
export function firstYearSchedule(
  animal: { sex: "F" | "M"; birthOn: ISODate },
  rules: RoutineRule[] = KENYA_ROUTINES,
): ScheduleItem[] {
  const { sex, birthOn } = animal;
  const items: ScheduleItem[] = [];

  items.push({
    routine: "COLOSTRUM",
    label: "Colostrum",
    dueOn: birthOn,
    windowClosesOn: addDays(birthOn, COLOSTRUM_DAYS),
    onceInLifetime: true,
    action:
      "Give 4 litres of colostrum in the first 6 hours, then keep her on it for 4 days. Do not put this milk in the can.",
    note: "The single biggest thing you can do for a calf, and it cannot be done late.",
    severity: "CRITICAL",
    assignedRole: "HERDSMAN",
  });

  for (const rule of rules) {
    if (rule.firstDoseMinAgeDays == null) continue;
    if (rule.firstDoseMinAgeDays > 365) continue;
    const elig = checkRoutineEligibility(rule, {
      sex,
      ageDays: rule.firstDoseMinAgeDays,
      alreadyGivenCount: 0,
    });
    if (!elig.eligible) continue;

    const dueOn = addDays(birthOn, rule.firstDoseMinAgeDays);
    const closesOn =
      rule.firstDoseMaxAgeDays != null ? addDays(birthOn, rule.firstDoseMaxAgeDays) : null;
    items.push({
      routine: rule.routine,
      label: rule.label,
      dueOn,
      windowClosesOn: closesOn,
      onceInLifetime: rule.onceInLifetime === true,
      action: routineAction(rule, dueOn, closesOn),
      note: rule.note,
      severity: closesOn ? "WARN" : "INFO",
      assignedRole: VACCINE_ROUTINES.has(rule.routine) ? "MANAGER" : "HERDSMAN",
    });
  }

  const weanOn = addDays(birthOn, Math.round(WEANING_AGE_MONTHS * 30.4375));
  items.push({
    routine: "WEANING",
    label: "Weaning target",
    dueOn: weanOn,
    windowClosesOn: null,
    onceInLifetime: true,
    action: `Weaning target ${weanOn} — she should be eating 1.5 kg of calf pellets a day before the milk stops.`,
    severity: "INFO",
    assignedRole: "HERDSMAN",
  });

  items.sort((a, b) => a.dueOn.localeCompare(b.dueOn) || a.routine.localeCompare(b.routine));
  return items;
}

/**
 * Persist the schedule as alerts. Keyed on animal + routine, so a replayed
 * offline registration adds nothing the second time.
 */
async function writeSchedule(
  session: Session,
  animalId: string,
  items: ScheduleItem[],
): Promise<void> {
  if (items.length === 0) return;
  await db
    .insert(s.alert)
    .values(
      items.map((i) => ({
        id: newId(),
        farmId: session.farmId,
        kind: `${ROUTINE_ALERT_PREFIX}${i.routine}`,
        animalId,
        assignedRole: i.assignedRole as s.Role,
        action: i.action,
        dueOn: i.dueOn,
        severity: i.severity,
        dedupeKey: `${animalId}:${ROUTINE_ALERT_PREFIX}${i.routine}`,
      })),
    )
    .onConflictDoNothing();
}

/* ================================================================== */
/* Action — register an animal                                         */
/* ================================================================== */

const RegisterInput = z.object({
  /** Client-generated so a double-flush from the outbox is a no-op. */
  id: z.string().uuid().optional(),
  tag: z.string().min(1, "Give her an ear tag number.").max(40),
  name: z.string().max(60).optional(),
  sex: z.enum(["F", "M"], { errorMap: () => ({ message: "Choose female or male." }) }),
  primaryBreed: z.string().max(40).optional(),
  breedComposition: z.string().max(80).optional(),
  dateOfBirth: isoDate.optional(),
  dobEstimated: checkbox,
  origin: z.enum(["BORN", "PURCHASED", "GIFT", "DONATION"]).default("BORN"),
  enteredHerdOn: isoDate.optional(),
  damId: z.string().uuid().optional(),
  sireId: z.string().uuid().optional(),
  sireStrawCode: z.string().max(40).optional(),
  purchasePriceKes: z.coerce.number().min(0).optional(),
  klbaRegNo: z.string().max(40).optional(),
  classOverride: z.enum(s.ANIMAL_CLASSES).optional(),
  castrated: checkbox,
  notes: z.string().max(500).optional(),
});

export interface RegisterAnimalResult {
  id: string;
  tag: string;
  name: string | null;
  cls: AnimalClass;
  classLabel: string;
  /** R7 — shown at the moment of entry, not next month. */
  schedule: ScheduleItem[];
}

export async function registerAnimal(
  _prev: unknown,
  formData: FormData,
): Promise<ActionResult<RegisterAnimalResult>> {
  "use server";
  return guard(async () => {
    // 1. Capability. Changing the herd register is an ADMIN act.
    const session = await requireCapability("ADMIN");

    // 2. Shape.
    const parsed = RegisterInput.safeParse(formObject(formData));
    if (!parsed.success) {
      return actionError("Check the highlighted fields.", parsed.error.flatten().fieldErrors);
    }
    const v = parsed.data;
    const enteredHerdOn = v.enteredHerdOn ?? v.dateOfBirth ?? today();

    // 3. Ownership — a well-formed dam UUID can belong to another farm.
    if (v.damId) {
      const dam = await db.query.animal.findFirst({
        where: and(eq(s.animal.id, v.damId), eq(s.animal.farmId, session.farmId)),
      });
      assertOwned(dam, session, "dam");
    }
    if (v.sireId) {
      const sire = await db.query.animal.findFirst({
        where: and(eq(s.animal.id, v.sireId), eq(s.animal.farmId, session.farmId)),
      });
      assertOwned(sire, session, "sire");
    }

    const duplicate = await db.query.animal.findFirst({
      where: and(eq(s.animal.farmId, session.farmId), eq(s.animal.tag, v.tag)),
    });
    if (duplicate && duplicate.id !== v.id) {
      return actionError("That tag is already on another animal.", {
        tag: [`Tag ${v.tag} belongs to ${duplicate.name ?? "another animal"}.`],
      });
    }

    // 4. Write. Client id + onConflictDoNothing = offline-safe.
    const id = v.id ?? newId();
    await db
      .insert(s.animal)
      .values({
        id,
        farmId: session.farmId,
        tag: v.tag,
        name: v.name ?? null,
        sex: v.sex,
        primaryBreed: v.primaryBreed ?? null,
        breedComposition: v.breedComposition ?? null,
        dateOfBirth: v.dateOfBirth ?? null,
        dobEstimated: v.dobEstimated,
        sireId: v.sireId ?? null,
        damId: v.damId ?? null,
        sireStrawCode: v.sireStrawCode ?? null,
        origin: v.origin,
        enteredHerdOn,
        purchasePriceKes: v.purchasePriceKes != null ? dec(v.purchasePriceKes) : null,
        klbaRegNo: v.klbaRegNo ?? null,
        classOverride: v.classOverride ?? null,
        castrated: v.castrated,
        notes: v.notes ?? null,
      })
      .onConflictDoNothing();

    // 5. R7 — the first year of reminders, generated and shown now.
    const born = v.dateOfBirth;
    const youngEnough = born != null && (ageDays(born, enteredHerdOn) ?? 9999) <= 365;
    const schedule = youngEnough ? firstYearSchedule({ sex: v.sex, birthOn: born! }) : [];
    if (schedule.length) await writeSchedule(session, id, schedule);

    const facts: AnimalFacts = {
      sex: v.sex,
      dateOfBirth: v.dateOfBirth ?? null,
      castrated: v.castrated,
      classOverride: v.classOverride ?? null,
      parity: 0,
      lastCalvingOn: null,
      lastServiceOn: null,
      pdPositiveOn: null,
      pdNegativeOn: null,
      driedOffOn: null,
      expectedCalvingOn: null,
      latestWeightKg: null,
      culled: false,
    };
    const cls = deriveClass(facts, today());

    // 6. Receipt (R6).
    const who = v.name ? `${v.name} (${v.tag})` : v.tag;
    const ref = await writeReceipt(session, {
      id,
      prefix: HERD_REF.ANIMAL,
      kind: "ANIMAL_REGISTERED",
      summary:
        schedule.length > 0
          ? `${who} added to the herd. ${schedule.length} reminders set for her first year.`
          : `${who} added to the herd.`,
      payload: { animalId: id, schedule },
    });

    updateTag(`herd:${session.farmId}`);

    return actionOk(
      { id, tag: v.tag, name: v.name ?? null, cls, classLabel: CLASS_LABEL[cls], schedule },
      schedule.length > 0
        ? `${who} is registered. Here is her first year.`
        : born
          ? `${who} is registered.`
          : `${who} is registered. Add her date of birth to get her vaccination dates.`,
      ref,
    );
  });
}

/* ================================================================== */
/* Action — weight and body condition                                  */
/* ================================================================== */

const WeightInput = z
  .object({
    id: z.string().uuid().optional(),
    animalId: z.string().uuid("Choose an animal."),
    observedOn: isoDate.optional(),
    weightKg: z.coerce.number().positive().max(2000).optional(),
    method: z.enum(["SCALE", "HEART_GIRTH", "ESTIMATE"]).optional(),
    bcs: z.coerce
      .number()
      .min(1, "Body condition runs from 1 to 5.")
      .max(5, "Body condition runs from 1 to 5.")
      .optional(),
  })
  .refine((v) => v.weightKg != null || v.bcs != null, {
    message: "Record a weight, a body condition score, or both.",
    path: ["weightKg"],
  });

export interface WeightResult {
  id: string;
  weightKg: number | null;
  bcs: number | null;
  /** R7 — the number that means something: growth since last time. */
  gainGramsPerDay: number | null;
  sinceDays: number | null;
  warnings: string[];
}

export async function recordWeight(
  _prev: unknown,
  formData: FormData,
): Promise<ActionResult<WeightResult>> {
  "use server";
  return guard(async () => {
    const session = await requireCapability("RECORD");

    const parsed = WeightInput.safeParse(formObject(formData));
    if (!parsed.success) {
      return actionError("Check the highlighted fields.", parsed.error.flatten().fieldErrors);
    }
    const v = parsed.data;
    const observedOn = v.observedOn ?? today();

    const animal = await db.query.animal.findFirst({
      where: and(eq(s.animal.id, v.animalId), eq(s.animal.farmId, session.farmId)),
    });
    assertOwned(animal, session, "animal");

    const warnings: string[] = [];

    // BCS is a five-point scale in quarter steps. Snapping is a correction, not
    // a rejection — R4 means we never throw the entry away.
    let bcs: number | null = null;
    if (v.bcs != null) {
      bcs = Math.round(v.bcs * 4) / 4;
      if (bcs !== v.bcs) {
        warnings.push(`Body condition is scored in quarter steps — saved as ${bcs.toFixed(2)}.`);
      }
    }

    // R4 again: an implausible weight is flagged, never refused.
    if (v.weightKg != null) {
      const months = ageMonths(animal!.dateOfBirth, observedOn);
      if (v.weightKg > 900) warnings.push("That is very heavy for a dairy cow — check the reading.");
      if (v.weightKg < 20) warnings.push("That is very light — check the reading.");
      if (months != null && months < 6 && v.weightKg > 250) {
        warnings.push("That is heavy for a calf under six months — check the reading.");
      }
    }

    const previous = await db
      .select()
      .from(s.weightObservation)
      .where(
        and(
          eq(s.weightObservation.farmId, session.farmId),
          eq(s.weightObservation.animalId, v.animalId),
        ),
      );
    const priorWeights = previous
      .filter((r) => r.weightKg != null && r.observedOn < observedOn)
      .sort((a, b) => a.observedOn.localeCompare(b.observedOn));
    const last = priorWeights.length ? priorWeights[priorWeights.length - 1] : null;

    let gain: number | null = null;
    let sinceDays: number | null = null;
    if (last && v.weightKg != null) {
      sinceDays = daysBetween(last.observedOn, observedOn);
      if (sinceDays > 0) {
        gain = Math.round(((v.weightKg - num(last.weightKg)) * 1000) / sinceDays);
      }
    }

    const id = v.id ?? newId();
    await db
      .insert(s.weightObservation)
      .values({
        id,
        farmId: session.farmId,
        animalId: v.animalId,
        observedOn,
        weightKg: v.weightKg != null ? dec(v.weightKg) : null,
        method: v.method ?? null,
        bcs: bcs != null ? dec(bcs) : null,
        recordedBy: session.userId,
      })
      .onConflictDoNothing();

    const who = animal!.name ?? animal!.tag;
    const parts: string[] = [];
    if (v.weightKg != null) parts.push(`${v.weightKg} kg`);
    if (bcs != null) parts.push(`body condition ${bcs.toFixed(2)}`);
    let message = `${who}: ${parts.join(", ")} recorded.`;
    if (gain != null) {
      message +=
        gain >= 0
          ? ` She has gained ${gain} g a day since ${last!.observedOn}.`
          : ` She has LOST ${Math.abs(gain)} g a day since ${last!.observedOn}.`;
    }

    const ref = await writeReceipt(session, {
      id,
      prefix: HERD_REF.WEIGHT,
      kind: "WEIGHT",
      summary: message,
      payload: { animalId: v.animalId, weightKg: v.weightKg ?? null, bcs },
    });

    updateTag(`herd:${session.farmId}`);

    return actionOk(
      { id, weightKg: v.weightKg ?? null, bcs, gainGramsPerDay: gain, sinceDays, warnings },
      message,
      ref,
    );
  });
}

/* ================================================================== */
/* Action — exit                                                       */
/* ================================================================== */

const ExitInput = z.object({
  id: z.string().uuid().optional(),
  animalId: z.string().uuid("Choose an animal."),
  exitDate: isoDate.optional(),
  reason: z.enum(["SOLD", "DIED", "SLAUGHTERED", "CULLED", "STOLEN", "LOST"]),
  cause: z.string().max(200).optional(),
  valueKes: z.coerce.number().min(0).optional(),
  counterpartyId: z.string().uuid().optional(),
  // The Kenyan price drivers — what a buyer actually pays for.
  weightKg: z.coerce.number().positive().max(2000).optional(),
  monthsPregnant: z.coerce.number().min(0).max(10).optional(),
  dailyYieldAtSaleL: z.coerce.number().min(0).max(80).optional(),
  daysInMilkAtSale: z.coerce.number().int().min(0).max(1500).optional(),
});

export interface ExitResult {
  id: string;
  classAtExit: AnimalClass;
  classLabel: string;
  daysInMilkAtSale: number | null;
  valueKes: number | null;
  warnings: string[];
}

export async function recordExit(
  _prev: unknown,
  formData: FormData,
): Promise<ActionResult<ExitResult>> {
  "use server";
  return guard(async () => {
    const session = await requireCapability("ADMIN");

    const parsed = ExitInput.safeParse(formObject(formData));
    if (!parsed.success) {
      return actionError("Check the highlighted fields.", parsed.error.flatten().fieldErrors);
    }
    const v = parsed.data;
    const exitDate = v.exitDate ?? today();

    const animal = await db.query.animal.findFirst({
      where: and(eq(s.animal.id, v.animalId), eq(s.animal.farmId, session.farmId)),
    });
    assertOwned(animal, session, "animal");

    const { events } = await loadHerdSources(session, { animalIds: [v.animalId] });
    const ev = events.get(v.animalId) ?? emptyEvents();

    const already = ev.exits.find((e) => e.id !== v.id);
    if (already) {
      return actionError(
        `${animal!.name ?? animal!.tag} already left the herd on ${already.exitDate} (${already.reason.toLowerCase()}).`,
      );
    }

    const facts = factsFor(animal!, ev, exitDate);
    const cls = deriveClass(facts, exitDate);
    const status = deriveReproStatus(facts, exitDate);
    const dim = v.daysInMilkAtSale ?? dimOf(facts, exitDate);

    const warnings: string[] = [];
    if (status === "PREGNANT" && v.monthsPregnant == null) {
      warnings.push("She is in calf — record how many months, it is most of what she is worth.");
    }
    if (isMilking(cls) && v.dailyYieldAtSaleL == null) {
      warnings.push("Record what she was giving a day — a buyer pays for litres, not for looks.");
    }
    if (v.reason === "DIED" && !v.cause) {
      warnings.push("Record what she died of, even a guess. It is the only way to see a pattern.");
    }

    const id = v.id ?? newId();
    await db
      .insert(s.animalExit)
      .values({
        id,
        farmId: session.farmId,
        animalId: v.animalId,
        exitDate,
        reason: v.reason,
        cause: v.cause ?? null,
        valueKes: v.valueKes != null ? dec(v.valueKes) : null,
        counterpartyId: v.counterpartyId ?? null,
        classAtExit: cls,
        weightKg: v.weightKg != null ? dec(v.weightKg) : null,
        monthsPregnant: v.monthsPregnant != null ? dec(v.monthsPregnant, 1) : null,
        dailyYieldAtSaleL: v.dailyYieldAtSaleL != null ? dec(v.dailyYieldAtSaleL) : null,
        daysInMilkAtSale: dim ?? null,
        recordedBy: session.userId,
      })
      .onConflictDoNothing();

    // She is gone; nothing outstanding on her is anybody's job any more.
    await db
      .update(s.alert)
      .set({ resolvedAt: new Date(), outcome: `ANIMAL_${v.reason}`, resolvedBy: session.userId })
      .where(
        and(
          eq(s.alert.farmId, session.farmId),
          eq(s.alert.animalId, v.animalId),
          isNull(s.alert.resolvedAt),
        ),
      );

    const who = animal!.name ?? animal!.tag;
    const REASON_WORD: Record<typeof v.reason, string> = {
      SOLD: "sold",
      DIED: "died",
      SLAUGHTERED: "slaughtered",
      CULLED: "culled",
      STOLEN: "stolen",
      LOST: "lost",
    };
    const message =
      `${who} ${REASON_WORD[v.reason]} on ${exitDate} as a ${CLASS_LABEL[cls].toLowerCase()}` +
      (v.valueKes != null ? ` for KES ${v.valueKes.toLocaleString("en-KE")}.` : ".");

    const ref = await writeReceipt(session, {
      id,
      prefix: REF_PREFIX.SALE,
      kind: "ANIMAL_EXIT",
      summary: message,
      payload: { animalId: v.animalId, reason: v.reason, classAtExit: cls },
    });

    updateTag(`herd:${session.farmId}`);

    return actionOk(
      {
        id,
        classAtExit: cls,
        classLabel: CLASS_LABEL[cls],
        daysInMilkAtSale: dim ?? null,
        valueKes: v.valueKes ?? null,
        warnings,
      },
      message,
      ref,
    );
  });
}

/* ================================================================== */
/* Query — the herd list                                               */
/* ================================================================== */

export interface HerdRow {
  id: string;
  tag: string;
  name: string | null;
  sex: "F" | "M";
  primaryBreed: string | null;
  breedComposition: string | null;
  dateOfBirth: ISODate | null;
  dobEstimated: boolean;
  ageMonths: number | null;
  /** Derived, always. There is no class column and there never will be. */
  cls: AnimalClass;
  classLabel: string;
  classIsOverridden: boolean;
  reproStatus: ReproStatus;
  daysInMilk: number | null;
  parity: number;
  lastCalvingOn: ISODate | null;
  lastServiceOn: ISODate | null;
  expectedCalvingOn: ISODate | null;
  latestWeightKg: number | null;
  latestBcs: number | null;
  latestWeightOn: ISODate | null;
  milking: boolean;
  exited: boolean;
  exitDate: ISODate | null;
  exitReason: string | null;
}

export interface ListHerdOptions {
  asOf?: ISODate;
  /** Filter on the DERIVED class, after derivation. */
  cls?: AnimalClass | null;
  /** Matches name or tag, case-insensitive, anywhere in the string. */
  search?: string | null;
  includeExited?: boolean;
  sex?: "F" | "M" | null;
}

export interface HerdList {
  asOf: ISODate;
  rows: HerdRow[];
  /** Counts across the whole herd, not just the filtered page. */
  countsByClass: Record<string, number>;
  total: number;
  milkingCount: number;
}

export async function listHerd(session: Session, opts: ListHerdOptions = {}): Promise<HerdList> {
  const asOf = opts.asOf ?? today();
  const { animals, events } = await loadHerdSources(session);

  const all: HerdRow[] = animals.map((a) => {
    const ev = events.get(a.id) ?? emptyEvents();
    const facts = factsFor(a, ev, asOf);
    const cls = deriveClass(facts, asOf);
    const status = deriveReproStatus(facts, asOf);
    const weights = ev.weights.filter((w) => w.observedOn <= asOf);
    const lastWeight = [...weights].reverse().find((w) => w.weightKg != null) ?? null;
    const lastBcs = [...weights].reverse().find((w) => w.bcs != null) ?? null;
    const exit = ev.exits.find((e) => e.exitDate <= asOf) ?? null;

    return {
      id: a.id,
      tag: a.tag,
      name: a.name,
      sex: a.sex,
      primaryBreed: a.primaryBreed,
      breedComposition: a.breedComposition,
      dateOfBirth: a.dateOfBirth,
      dobEstimated: a.dobEstimated,
      ageMonths: a.dateOfBirth ? Math.floor(ageMonths(a.dateOfBirth, asOf)!) : null,
      cls,
      classLabel: CLASS_LABEL[cls],
      classIsOverridden: a.classOverride != null,
      reproStatus: status,
      daysInMilk: dimOf(facts, asOf),
      parity: facts.parity,
      lastCalvingOn: facts.lastCalvingOn,
      lastServiceOn: facts.lastServiceOn,
      expectedCalvingOn: status === "PREGNANT" ? facts.expectedCalvingOn : null,
      latestWeightKg: lastWeight ? num(lastWeight.weightKg) : null,
      latestBcs: lastBcs ? num(lastBcs.bcs) : null,
      latestWeightOn: lastWeight?.observedOn ?? null,
      milking: isMilking(cls) && status !== "DRY",
      exited: exit != null,
      exitDate: exit?.exitDate ?? null,
      exitReason: exit?.reason ?? null,
    };
  });

  const inHerd = all.filter((r) => opts.includeExited || !r.exited);

  const countsByClass: Record<string, number> = {};
  for (const r of inHerd) countsByClass[r.cls] = (countsByClass[r.cls] ?? 0) + 1;

  const needle = opts.search?.trim().toLowerCase() ?? "";
  const rows = inHerd
    .filter((r) => (opts.cls ? r.cls === opts.cls : true))
    .filter((r) => (opts.sex ? r.sex === opts.sex : true))
    .filter((r) =>
      needle === ""
        ? true
        : r.tag.toLowerCase().includes(needle) || (r.name ?? "").toLowerCase().includes(needle),
    )
    .sort(
      (a, b) =>
        a.cls.localeCompare(b.cls) ||
        (a.name ?? a.tag).localeCompare(b.name ?? b.tag) ||
        a.tag.localeCompare(b.tag),
    );

  return {
    asOf,
    rows,
    countsByClass,
    total: inHerd.length,
    milkingCount: inHerd.filter((r) => r.milking).length,
  };
}

/* ================================================================== */
/* Query — the digital cow card                                        */
/* ================================================================== */

export interface LactationSummary {
  number: number;
  calvedOn: ISODate;
  endedOn: ISODate | null;
  /** Null while it is still running — use `daysSoFar` then. */
  lengthDays: number | null;
  daysSoFar: number;
  totalLitres: number;
  peakDailyLitres: number;
  recordedDays: number;
  calvingIntervalDays: number | null;
  servicesToConceive: number | null;
  daysOpen: number | null;
  ongoing: boolean;
}

export interface CowCard {
  asOf: ISODate;
  animal: AnimalRow;
  dam: { id: string; tag: string; name: string | null } | null;
  sire: { id: string; tag: string; name: string | null } | null;
  facts: AnimalFacts;
  cls: AnimalClass;
  classLabel: string;
  reproStatus: ReproStatus;
  daysInMilk: number | null;
  ageMonths: number | null;
  services: (ServiceRow & { returnInterpretationDays: number | null })[];
  pregnancyChecks: PdRow[];
  calvings: CalvingRow[];
  dryOffs: DryOffRow[];
  heats: HeatRow[];
  weights: WeightRow[];
  lactations: LactationSummary[];
  healthEvents: (typeof s.healthEvent.$inferSelect)[];
  openAlerts: (typeof s.alert.$inferSelect)[];
  offspring: { id: string; tag: string; name: string | null; dateOfBirth: ISODate | null; sex: "F" | "M" }[];
  exit: ExitRow | null;
  /** Present for animals still inside their first year. */
  schedule: ScheduleItem[];
}

export async function getAnimal(
  session: Session,
  animalId: string,
  opts: { asOf?: ISODate } = {},
): Promise<CowCard | null> {
  const asOf = opts.asOf ?? today();

  const animal = await db.query.animal.findFirst({
    where: and(eq(s.animal.id, animalId), eq(s.animal.farmId, session.farmId)),
  });
  if (!animal) return null;

  const { events } = await loadHerdSources(session, { animalIds: [animalId] });
  const ev = events.get(animalId) ?? emptyEvents();
  const facts = factsFor(animal, ev, asOf);
  const cls = deriveClass(facts, asOf);

  const [health, alerts, offspring, parents] = await Promise.all([
    db
      .select()
      .from(s.healthEvent)
      .where(and(eq(s.healthEvent.farmId, session.farmId), eq(s.healthEvent.animalId, animalId))),
    db.select().from(s.alert).where(and(eq(s.alert.farmId, session.farmId), eq(s.alert.animalId, animalId))),
    db
      .select()
      .from(s.animal)
      .where(and(eq(s.animal.farmId, session.farmId), eq(s.animal.damId, animalId))),
    animal.damId || animal.sireId
      ? db
          .select()
          .from(s.animal)
          .where(
            and(
              eq(s.animal.farmId, session.farmId),
              inArray(s.animal.id, [animal.damId, animal.sireId].filter(Boolean) as string[]),
            ),
          )
      : Promise.resolve([] as AnimalRow[]),
  ]);

  const milk = await db
    .select()
    .from(s.milkRecord)
    .where(and(eq(s.milkRecord.farmId, session.farmId), eq(s.milkRecord.animalId, animalId)));

  const lactations = buildLactations(animal, ev, milk, asOf);

  // Each service annotated with how long after the previous one it fell — the
  // raw material for the return-to-heat verdict on the breeding screen.
  const services = ev.services.map((r, i) => ({
    ...r,
    returnInterpretationDays: i > 0 ? daysBetween(ev.services[i - 1].servedOn, r.servedOn) : null,
  }));

  const born = animal.dateOfBirth;
  const schedule =
    born && (ageDays(born, asOf) ?? 9999) <= 365 ? firstYearSchedule({ sex: animal.sex, birthOn: born }) : [];

  const find = (id: string | null) => {
    const p = parents.find((x) => x.id === id);
    return p ? { id: p.id, tag: p.tag, name: p.name } : null;
  };

  return {
    asOf,
    animal,
    dam: find(animal.damId),
    sire: find(animal.sireId),
    facts,
    cls,
    classLabel: CLASS_LABEL[cls],
    reproStatus: deriveReproStatus(facts, asOf),
    daysInMilk: dimOf(facts, asOf),
    ageMonths: animal.dateOfBirth ? Math.floor(ageMonths(animal.dateOfBirth, asOf)!) : null,
    services,
    pregnancyChecks: ev.pds,
    calvings: ev.calvings,
    dryOffs: ev.dryOffs,
    heats: ev.heats,
    weights: ev.weights,
    lactations,
    healthEvents: health.sort((a, b) => b.occurredOn.localeCompare(a.occurredOn)),
    openAlerts: alerts
      .filter((a) => a.resolvedAt == null)
      .sort((a, b) => a.dueOn.localeCompare(b.dueOn)),
    offspring: offspring
      .map((o) => ({ id: o.id, tag: o.tag, name: o.name, dateOfBirth: o.dateOfBirth, sex: o.sex }))
      .sort((a, b) => (b.dateOfBirth ?? "").localeCompare(a.dateOfBirth ?? "")),
    exit: ev.exits[0] ?? null,
    schedule,
  };
}

function buildLactations(
  animal: AnimalRow,
  ev: AnimalEvents,
  milk: (typeof s.milkRecord.$inferSelect)[],
  asOf: ISODate,
): LactationSummary[] {
  const calvings = ev.calvings.filter((c) => !isAbortionCalving(c) && c.calvedOn <= asOf);
  const out: LactationSummary[] = [];

  for (let i = 0; i < calvings.length; i++) {
    const start = calvings[i].calvedOn;
    const nextCalving = calvings[i + 1]?.calvedOn ?? null;
    const dry = ev.dryOffs.find((d) => d.driedOn > start && (!nextCalving || d.driedOn < nextCalving));
    const endedOn = dry?.driedOn ?? nextCalving ?? null;
    const upTo = endedOn ?? asOf;

    const days = milk.filter((m) => m.recordedOn >= start && m.recordedOn <= upTo);
    const byDay = new Map<string, number>();
    for (const m of days) byDay.set(m.recordedOn, (byDay.get(m.recordedOn) ?? 0) + num(m.litres));
    const totals = [...byDay.values()];

    // The service that got her back in calf, for days-open on the NEXT calving.
    const conceiving = nextCalving
      ? [...ev.services].reverse().find((r) => r.servedOn > start && r.servedOn < nextCalving)
      : null;
    const servicesInWindow = ev.services.filter(
      (r) => r.servedOn > start && (!nextCalving || r.servedOn < nextCalving),
    );

    out.push({
      number: i + 1,
      calvedOn: start,
      endedOn,
      lengthDays: endedOn ? daysBetween(start, endedOn) : null,
      daysSoFar: daysBetween(start, upTo),
      totalLitres: Math.round(totals.reduce((a, b) => a + b, 0) * 100) / 100,
      peakDailyLitres: totals.length ? Math.max(...totals) : 0,
      recordedDays: byDay.size,
      calvingIntervalDays: i > 0 ? calvingInterval(calvings[i - 1].calvedOn, start) : null,
      servicesToConceive: nextCalving
        ? Math.round(servicesPerConception(servicesInWindow.length, 1) * 10) / 10
        : null,
      daysOpen: conceiving ? daysBetween(start, conceiving.servedOn) : null,
      ongoing: endedOn == null,
    });
  }

  // A heifer who has never calved still deserves an honest empty answer.
  void animal;
  return out;
}

/* ================================================================== */
/* Query — inventory reconciliation                                    */
/* ================================================================== */

export interface InventoryReconciliation {
  from: ISODate;
  to: ISODate;
  opening: number;
  births: number;
  purchases: number;
  otherIn: number;
  deaths: number;
  sales: number;
  otherOut: number;
  closing: number;
  /** opening + births + purchases + otherIn − deaths − sales − otherOut */
  computedClosing: number;
  balances: boolean;
  difference: number;
  byExitReason: Record<string, number>;
  /** Plain language, for a screen a farmer reads rather than an auditor. */
  narrative: string;
}

/**
 * Opening + births + purchases − deaths − sales = closing.
 *
 * This is the number a co-operative, an insurer or a bank asks for, and the one
 * a farm can never produce from a notebook. It is derived entirely from
 * `enteredHerdOn` and `animal_exit`, so it cannot drift from the register.
 */
export async function herdInventoryReconciliation(
  session: Session,
  from: ISODate,
  to: ISODate,
): Promise<InventoryReconciliation> {
  const animals = await db.select().from(s.animal).where(eq(s.animal.farmId, session.farmId));
  const exits = await db
    .select()
    .from(s.animalExit)
    .where(eq(s.animalExit.farmId, session.farmId));

  const exitOf = new Map<string, ExitRow>();
  for (const e of exits) {
    const prev = exitOf.get(e.animalId);
    if (!prev || e.exitDate < prev.exitDate) exitOf.set(e.animalId, e);
  }

  const present = (a: AnimalRow, on: ISODate) => {
    if (a.enteredHerdOn > on) return false;
    const e = exitOf.get(a.id);
    return !e || e.exitDate > on;
  };

  const dayBefore = addDays(from, -1);
  const opening = animals.filter((a) => present(a, dayBefore)).length;
  const closing = animals.filter((a) => present(a, to)).length;

  const arrivals = animals.filter((a) => a.enteredHerdOn >= from && a.enteredHerdOn <= to);
  const births = arrivals.filter((a) => a.origin === "BORN").length;
  const purchases = arrivals.filter((a) => a.origin === "PURCHASED").length;
  const otherIn = arrivals.length - births - purchases;

  const departures = exits.filter((e) => e.exitDate >= from && e.exitDate <= to);
  const byExitReason: Record<string, number> = {};
  for (const e of departures) byExitReason[e.reason] = (byExitReason[e.reason] ?? 0) + 1;

  const deaths = departures.filter((e) => e.reason === "DIED").length;
  const sales = departures.filter((e) => e.reason === "SOLD" || e.reason === "CULLED").length;
  const otherOut = departures.length - deaths - sales;

  const computedClosing = opening + births + purchases + otherIn - deaths - sales - otherOut;
  const difference = closing - computedClosing;

  const narrative =
    `You started with ${opening}. ${births} born, ${purchases} bought` +
    (otherIn ? `, ${otherIn} in another way` : "") +
    `; ${deaths} died, ${sales} sold or culled` +
    (otherOut ? `, ${otherOut} left another way` : "") +
    `. You should have ${computedClosing} — the register says ${closing}.` +
    (difference === 0 ? " It balances." : ` That is ${Math.abs(difference)} out.`);

  return {
    from,
    to,
    opening,
    births,
    purchases,
    otherIn,
    deaths,
    sales,
    otherOut,
    closing,
    computedClosing,
    balances: difference === 0,
    difference,
    byExitReason,
    narrative,
  };
}

/* ================================================================== */
/* Query — small helpers the breeding screens need                     */
/* ================================================================== */

/** Animals that can sensibly appear in a breeding picker. */
export async function listBreedingCandidates(
  session: Session,
  opts: { asOf?: ISODate } = {},
): Promise<HerdRow[]> {
  const list = await listHerd(session, { asOf: opts.asOf });
  return list.rows.filter((r) => r.sex === "F" && r.cls !== "CALF" && r.cls !== "WEANER");
}
